# Generated by Django 3.1 on 2020-08-29 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_avaliacaocliente_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=48)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemKit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qntd', models.PositiveIntegerField(default=1)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.kit')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.produto')),
            ],
        ),
    ]
