# Generated by Django 3.1 on 2020-08-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_itemkit_kit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Mensagens do site',
            },
        ),
        migrations.AlterModelOptions(
            name='avaliacaocliente',
            options={'verbose_name_plural': 'Avaliações dos produtos'},
        ),
        migrations.AlterModelOptions(
            name='itemkit',
            options={'verbose_name_plural': 'Itens em kits'},
        ),
    ]
