# Generated by Django 3.1 on 2020-08-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200829_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaocliente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='avaliacaocliente',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itemkit',
            name='kit',
        ),
        migrations.RemoveField(
            model_name='itemkit',
            name='produto',
        ),
        migrations.DeleteModel(
            name='MensagemSite',
        ),
        migrations.DeleteModel(
            name='AvaliacaoCliente',
        ),
        migrations.DeleteModel(
            name='ItemKit',
        ),
        migrations.DeleteModel(
            name='Kit',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
