# Generated by Django 3.1 on 2020-08-30 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_avaliacaocliente_itemkit_kit_mensagemsite_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link da imagem'),
        ),
        migrations.AlterField(
            model_name='avaliacaocliente',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação no banco de dados'),
        ),
        migrations.AlterField(
            model_name='avaliacaocliente',
            name='pontuacao',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Pontuação (0-5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaocliente',
            name='titulo',
            field=models.CharField(max_length=48, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='itemkit',
            name='qntd',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação no banco de dados'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='mensagemsite',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação no banco de dados'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação no banco de dados'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qntd_estoque',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade em estoque'),
        ),
    ]
