# Generated by Django 3.1 on 2020-09-01 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20200831_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qntd', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.kit')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.produto')),
            ],
            options={
                'verbose_name_plural': 'Ítens em carrinhos',
            },
        ),
    ]
