# Generated by Django 3.1 on 2020-09-01 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
