# Generated by Django 3.1 on 2020-09-01 04:40

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=48)),
                ('conteudo', martor.models.MartorField()),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação no banco de dados')),
            ],
            options={
                'verbose_name_plural': 'Artigos do blog',
            },
        ),
    ]
