# Generated by Django 3.1 on 2020-09-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_blogpost_imagem_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imagem_capa',
            field=models.FileField(null=True, upload_to='capas_artigos'),
        ),
    ]
