# Generated by Django 3.1 on 2020-09-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20200901_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.FileField(null=True, upload_to='imagens_produtos'),
        ),
    ]
