# Generated by Django 3.1 on 2020-09-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20200901_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Mostrar no site'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Mostrar no site'),
        ),
    ]
