# Generated by Django 3.1 on 2020-09-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20200902_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaocliente',
            name='produto',
        ),
        migrations.AddField(
            model_name='kit',
            name='avaliacoes',
            field=models.ManyToManyField(to='webapp.AvaliacaoCliente'),
        ),
        migrations.AddField(
            model_name='produto',
            name='avaliacoes',
            field=models.ManyToManyField(to='webapp.AvaliacaoCliente'),
        ),
    ]
