# Generated by Django 3.1 on 2020-09-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20200907_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='produtos',
            field=models.ManyToManyField(to='webapp.Produto'),
        ),
        migrations.DeleteModel(
            name='ItemKit',
        ),
    ]
