# Generated by Django 3.1 on 2020-09-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20200907_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='foto',
            field=models.FileField(null=True, upload_to='imagens_kits'),
        ),
    ]
