# Generated by Django 3.1 on 2020-09-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_kit_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='titulo',
            field=models.CharField(max_length=96),
        ),
    ]
