# Generated by Django 3.1 on 2020-09-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20200907_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='descricao',
            field=models.CharField(default='', max_length=100, verbose_name='Descrição do artigo (100 caracteres)'),
        ),
    ]
