# Generated by Django 3.1 on 2020-09-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_blogpost_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='descricao',
            field=models.CharField(default='', max_length=200, verbose_name='Descrição do artigo (200 caracteres)'),
        ),
    ]
