# Generated by Django 3.1 on 2020-09-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20200911_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='produtos',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='imagem_capa',
            field=models.FileField(null=True, upload_to='capas_artigos', verbose_name='Imagem de capa'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='titulo',
            field=models.CharField(max_length=96, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.kit'),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.produto'),
        ),
        migrations.CreateModel(
            name='ProdutoKit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qntd', models.PositiveIntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.produto')),
            ],
            options={
                'verbose_name': 'Produto em kit',
                'verbose_name_plural': 'Produtos em kits',
            },
        ),
        migrations.AddField(
            model_name='kit',
            name='itens',
            field=models.ManyToManyField(to='webapp.ProdutoKit'),
        ),
    ]
