# Generated by Django 3.1 on 2020-10-19 00:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_auto_20200921_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemKitPersonalizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qntd', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.produto')),
            ],
            options={
                'verbose_name': 'Item de kit personalizado',
                'verbose_name_plural': 'Ítens de kits personalizados',
            },
        ),
        migrations.CreateModel(
            name='KitPersonalizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando aprovação'), ('aprovado', 'Aprovado'), ('negado', 'Negado')], max_length=10)),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email do cliente')),
                ('whatsapp_cliente', models.CharField(max_length=20, verbose_name='WhatsApp do cliente')),
                ('telefone_cliente', models.CharField(max_length=20, verbose_name='Telefone do cliente')),
                ('itens', models.ManyToManyField(to='webapp.ItemKitPersonalizado', verbose_name='Ítens no kit')),
            ],
        ),
    ]
