# Generated by Django 3.1 on 2020-11-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_itemkitpersonalizado_kitpersonalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitpersonalizado',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando aprovação'), ('aprovado', 'Aprovado'), ('negado', 'Negado')], default='aguardando', max_length=10),
        ),
    ]
